from __future__ import annotations

import typing as t

from sqlglot import expressions as exp


INDEX = "i"
ARG_KEY = "k"
IS_ARRAY = "a"
CLASS = "c"
TYPE = "t"
COMMENTS = "o"
META = "m"
VALUE = "v"
DATA_TYPE = "DataType.Type"


def dump(expression: exp.Expr) -> list[dict[str, t.Any]]:
    """
    Dump an Expr into a JSON serializable List.
    """
    pass


def load(
    payloads: list[dict[str, t.Any]] | None,
) -> exp.Expr | exp.DType | None:
    """
    Load a list of dicts generated by dump into an Expr.
    """

    if not payloads:
        return None

    payload, *tail = payloads
    root = _load(payload)
    nodes: list[object] = [root]
    for payload in tail:
        if CLASS in payload:
            node: object = _load(payload)
        else:
            node = payload[VALUE]

        nodes.append(node)
        parent = nodes[payload[INDEX]]
        arg_key = payload[ARG_KEY]

        if payload.get(IS_ARRAY):
            parent.append(arg_key, node)
        else:
            parent.set(arg_key, node)

    return root


def _load(payload: dict[str, t.Any]) -> exp.Expr | exp.DType:
    class_name = payload[CLASS]

    if class_name == DATA_TYPE:
        return exp.DType(payload[VALUE])

    if "." in class_name:
        module_path, class_name = class_name.rsplit(".", maxsplit=1)
        module = __import__(module_path, fromlist=[class_name])
    else:
        module = exp

    expression = getattr(module, class_name)()
    expression._type = load(payload.get(TYPE))
    expression.comments = payload.get(COMMENTS)
    expression._meta = payload.get(META)
    return expression
